### ISSUE TITLE
Is the Whitening of the input X appropriate?

### ISSUE THREAD

**Issue by whatlantic** [BerkeleyAutomation/DART#1]
In the "fit" function in "knet.py", you whiten the input X before calling "model.fit". I don't think the "whiten()"function is appropriate for the following reason.
Every time you whiten the input X, the mean and std values are different because they are calculated from different demonstrations. If the size of X is 1, subtracting X by its mean will result in 0 and the std of X will be 0.
Maybe I don't understand your code well enough. Would you please help explain this for me? Thank you.

**Comment by jon--lee** [comment]
Sure! The purpose of this function is to standardize the inputs. We found doing so generally gets better performance on Humanoid. A similar technique was used to obtain the supervisors. In this case, the mean and std are computed only at training time on the training set. From then on, they are fixed. So when new test inputs go in, the same mean and std are used to preprocess those inputs.

In your example, that is the intended result. There are some lines there to prevent numerical issues for special cases like this.

**Comment by whatlantic** [comment]
I see. So when I save the weights of the model, I have to save the mean and std values as well. Then I can use them for testing.
Thank you for your explanation.
